package com.maxkernchen.walkingalarm;

import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;

import android.app.KeyguardManager;
import android.app.PendingIntent;
import android.app.TaskStackBuilder;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;

import android.view.WindowManager;
import android.widget.TextView;

import com.maxkernchen.walkingalarm.databinding.ActivityAlarmFullScreenBinding;

/**
 * Full-Screen activity which will display a users progress towards dismissing the alarm.
 * Half of this class is auto-generated by Android Studio for compatibility between APIs
 * to hide System UI elements.
 *
 * The other half contains a broadcast receiver to dismiss or update the full screen UI elements.
 *
 * @version 1.4
 * @author Max Kernchen
 */
public class AlarmFullScreen extends AppCompatActivity {

    /**
     * public Static String for the Alarm Full Screen Notification Channel
     */
    public static final String CHANNEL_ID = "AlarmFullScreenChannel";
    /**
     * public Static String for the Walking Alarm Notification Channel
     */
    public static final String CHANNEL_NAME = "WalkingAlarmNotificationChannel";
    /**
     * public Static String for the Walking Alarm Notification Channel description.
     */
    public static final String CHANNEL_DESCRIPTION = "WalkingAlarmNotificationChannelDescription";

    /**
     * public Static String for the Alarm Full Screen Action that triggers the notification.
     */
    public static final String FULL_SCREEN_ACTION_ALARM = "AlarmActionFullScreen";
    /**
     * public Static String for the Alarm Full Screen Action that tracks steps walked so far.
     */
    public static final String WALK_ACTION = "AlarmActionWalk";
    /**
     * public Static String for the Alarm Full Screen Action that dismisses the notification.
     */
    public static final String DISMISS_ALARM_ACTION = "AlarmActionDismiss";
    /**
     * public Static String intent extra that stores current steps.
     */
    public static final String INTENT_EXTRA_STEPS = "StepsStringExtra";
    /**
     * public Static String intent extra that stores the alarm name.
     */
    public static final String INTENT_EXTRA_ALARM_NAME = "AlarmNameExtra";
    /**
     * public Static String intent extra that stores the alarm sound uri.
     */
    public static final String INTENT_EXTRA_ALARM_SOUND_URI = "AlarmSoundUriExtra";
    /**
     * public Static String intent extra that stores the alarm sound uri.
     */
    public static final String INTENT_EXTRA_ALARM_VIBRATE_BOOL = "AlarmVibrateBoolExtra";
    /**
     * public Static String intent extra that stores the alarm channel id.
     */
    public static final String INTENT_EXTRA_ALARM_CHANNEL_ID = "AlarmChannelIDExtra";
    /**
     * public Static int intent extra that stores notification id.
     */
    public static final int NOTIFICATION_ID_ALARM = 1;

    /** bool used to monitor when the Full Screen activity is created,
     *  these is always a few second delay between when we find an alarm and the notification
     *  reaches the users. This helps us know when to start monitoring user steps.
     */
    public static boolean isCreated = false;

    /**
     * Static vibration pattern to be used when vibration is enabled.
     */
    public static final long[] VIBRATION_PATTERN = new long[]{500, 1000, 500, 1000, 500, 1000};

    /** BroadcastReceiver for dismissing/updated the full screen activity UI. Called from
     *  AlarmReceiver
     */
    private BroadcastReceiver alarmFullScreenReceiver;

    /**
     * binding for our full screen activity
     */
    private ActivityAlarmFullScreenBinding binding;

    /**
     * Creates activity and also registers broadcast receiver for incoming Intents.
     * Also sets isCreated boolean = true.
     * @param savedInstanceState the current instance state
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        binding = ActivityAlarmFullScreenBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // set flags so activity is showed when phone is off (on lock screen)
        // and to remove status and action bar.

        setShowWhenLocked(true);
        setTurnScreenOn(true);
        KeyguardManager keyguardManager =
                (KeyguardManager)getSystemService(Context.KEYGUARD_SERVICE);
        keyguardManager.requestDismissKeyguard(this, null);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON |
                WindowManager.LayoutParams.FLAG_FULLSCREEN);

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.hide();
        }

        registerReceiver();
        isCreated = true;

    }
    /**
     * onStop is overridden here to unregister the broadcast receiver.
     */
    @Override
    public void onStop() {
        super.onStop();
        isCreated = false;
        if (alarmFullScreenReceiver != null) {
            unregisterReceiver(alarmFullScreenReceiver);
        }
    }

    /**
     * define our broadcast receiver, there are three filters.
     *
     * 1. WALK_ACTION -  update the UI with remaining steps to dismiss alarm
     * 2. DISMISS_ALARM_ACTION - dismisses the notification/full screen activity,
     *    goes back to previous activity.
     * 3. FULL_SCREEN_ACTION_ALARM - starts the notification/full screen activity.
     */
    private void registerReceiver() {
        alarmFullScreenReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                switch (intent.getAction()) {
                    case AlarmFullScreen.WALK_ACTION: {
                        int steps = intent.getIntExtra
                                (AlarmFullScreen.INTENT_EXTRA_STEPS, -1);
                        if (steps >= 0) {
                            TextView view = (TextView) findViewById(R.id.fullscreen_content);
                            view.setText(getString(R.string.alarm_steps_remaining, steps));
                        }
                        break;
                    }
                    case AlarmFullScreen.DISMISS_ALARM_ACTION: {
                        String alarmChanID = intent.getStringExtra(
                                AlarmFullScreen.INTENT_EXTRA_ALARM_CHANNEL_ID);
                        cancelFullScreenNotification(context, alarmChanID);
                        break;
                    }
                }
            }
        };
        IntentFilter filter = new IntentFilter();
        filter.addAction(AlarmFullScreen.WALK_ACTION);
        filter.addAction(AlarmFullScreen.DISMISS_ALARM_ACTION);
        registerReceiver(alarmFullScreenReceiver, filter);
    }


    /**
     * Cancel the current notification and move the full screen activity to the back.
     * @param context - context sent from AlarmReceiver.
     * @param alarmChannelID - the channel id of the alarm,
     *                       used to uniquely make each notification channel
     */
    private void cancelFullScreenNotification(Context context, String alarmChannelID) {
        isCreated = false;

        NotificationManagerCompat notificationManager = NotificationManagerCompat.from(context);
        notificationManager.cancel(AlarmFullScreen.NOTIFICATION_ID_ALARM);
        notificationManager.deleteNotificationChannel
                (AlarmFullScreen.CHANNEL_ID + alarmChannelID);

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.show();
        }
        moveTaskToBack(true);
        finish();
    }

    /**
     * Create the notification using context from alarm service.
     * @param context - context from alarm service.
     * @param alarmName - name of alarm to be used on notification text.
     * @param alarmChannelID - unique channel id for this notification
     * @param steps steps to dismiss to be used in notification subtext
     */
    public static void createFullScreenNotification(Context context, String alarmName,
                                                    String alarmChannelID,
                                                    int steps) {
        Intent intent = new Intent(context, AlarmFullScreen.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_NO_USER_ACTION |
                Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP) ;

        TaskStackBuilder stackBuilder = TaskStackBuilder.create(context);
        stackBuilder.addNextIntentWithParentStack(intent);

        int pendingFlag;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            pendingFlag = PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_UPDATE_CURRENT |
                    PendingIntent.FLAG_ONE_SHOT;
        } else {
            pendingFlag = PendingIntent.FLAG_UPDATE_CURRENT;
        }
        PendingIntent resultPendingIntent =
                stackBuilder.getPendingIntent(0,
                        pendingFlag);

        NotificationCompat.Builder notificationBuilder =
                new NotificationCompat.Builder(context, CHANNEL_ID + alarmChannelID)
                        .setSmallIcon(R.drawable.ic_walk_action_foreground)
                        .setContentTitle(context.getString(R.string.alarm_notification_text,
                                alarmName))
                        .setContentText(context.
                                getString(R.string.alarm_notification_subtext, steps))
                        .setPriority(NotificationCompat.PRIORITY_MAX)
                        .setCategory(NotificationCompat.CATEGORY_CALL)
                        .setContentIntent(resultPendingIntent)
                        .setFullScreenIntent(resultPendingIntent, true)
                        .setAutoCancel(false)
                        .setOngoing(true);

        NotificationManagerCompat notificationManager = NotificationManagerCompat.
                from(context);
        if (ActivityCompat.checkSelfPermission(context, android.Manifest.permission.POST_NOTIFICATIONS)
                != PackageManager.PERMISSION_GRANTED) {

            return;
        }
        notificationManager.notify(NOTIFICATION_ID_ALARM, notificationBuilder.build());

    }
}
